package snd.komelia.ui.strings

/**
 * 简体中文 (zh-CN) 翻译。
 *
 * 翻译规范见 `docs/i18n/glossary_zh-CN.md` 与 `docs/i18n/CONTRIBUTING_zh-CN.md`：
 * - 品牌名（Komelia / Komga / Komf）与第三方元数据提供方名称（AniList / Bangumi / MangaDex 等）保留原名
 * - 图像处理算法名（Lanczos / Mitchell / Catmull-Rom / MKS / ONNX 等）保留英文，避免误导
 * - 按钮使用动词，标题使用名词；避免句末加全角句号
 *
 * 注意：本文件仅翻译已被 `LocalStrings` 集中管理的字符串。
 * UI 中仍有大量硬编码英文字符串（约 580 处），将在后续 PR 中逐步迁移到 `AppStrings`，再补充翻译。
 */
val ZhCnStrings = AppStrings(
    common = CommonUiStrings(
        cancel = "取消",
        confirm = "确认",
        save = "保存",
        discard = "放弃",
        delete = "删除",
        edit = "编辑",
        close = "关闭",
        retry = "重试",
        reset = "重置",
        download = "下载",
        search = "搜索",
        error = "错误",
        nothingToShow = "暂无内容",
        copiedToClipboard = "已复制到剪贴板",
    ),
    mainNavigation = MainNavigationStrings(
        libraries = "书库",
        home = "首页",
        search = "搜索",
        settings = "设置",
        offline = "离线",
        goOnlineTitle = "切回在线模式？",
    ),
    settingsNavigation = SettingsNavigationStrings(
        appSettings = "应用设置",
        appearance = "外观",
        imageReader = "图像阅读器",
        epubReader = "EPUB 阅读器",
        updates = "更新",
        offlineMode = "离线模式",
        userSettings = "用户设置",
        myAccount = "我的账户",
        myAuthenticationActivity = "我的登录记录",
        serverSettings = "服务器设置",
        general = "通用",
        users = "用户",
        authenticationActivity = "登录记录",
        mediaManagement = "媒体分析",
        announcements = "通知",
        komfSettings = "Komf 设置",
        connection = "连接",
        processing = "处理",
        providers = "元数据源",
        notifications = "通知",
        jobHistory = "任务历史",
        logOut = "退出登录",
        logOutConfirmTitle = "退出登录",
        logOutConfirmBody = "确定要退出当前账户吗？",
    ),
    login = LoginStrings(
        komgaLogin = "Komga 登录",
        webClientSubtitle = "面向 Komga 的完整 Web 客户端",
        serverUrl = "服务器地址",
        username = "用户名",
        password = "密码",
        login = "登录",
        offlineMode = "离线模式",
        goOffline = "进入离线模式",
        backToOnline = "返回在线模式",
        loginWithAnotherAccount = "使用其他账户登录",
        cancelLoginAttempt = "取消登录",
        invalidServerUrl = "请输入有效的 HTTP 或 HTTPS 服务器地址",
        invalidServerPort = "端口必须在 1 到 65535 之间",
    ),
    filters = FilterStrings(
        anyValue = "任意",

        filterTagsSearch = "搜索标签",
        filterTagsReset = "重置",
        filterTagsGenreLabel = "类型",
        filterTagsTagsLabel = "标签",
        filterTagsShowMore = "展开",
        filterTagsShowLess = "收起",
        includeIfAllMatch = "全部匹配",
        includeIfAnyMatch = "任一匹配",
        excludeIfAllMatch = "全部匹配",
        excludeIfAnyMatch = "任一匹配",
    ),
    seriesFilter = SeriesFilterStrings(
        resetFilters = "重置筛选",
        hideFilters = "隐藏筛选",
        anyValue = "任意",
        search = "搜索",

        sort = "排序方式",
        sortTitleAsc = "标题升序",
        sortTitleDesc = "标题降序",
        sortDateAddedAsc = "最早添加",
        sortDateAddedDesc = "最近添加",
        sortReleaseDateAsc = "最早发布",
        sortReleaseDateDesc = "最新发布",
        sortUpdatedAsc = "最早更新",
        sortUpdatedDesc = "最近更新",
        sortFolderNameAsc = "文件夹名升序",
        sortFolderNameDesc = "文件夹名降序",
        sortBooksCountAsc = "书籍数从少到多",
        sortBooksCountDesc = "书籍数从多到少",

        filterTagsLabel = "筛选标签",
        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        publicationStatus = "出版状态",
        pubStatusEnded = "已完结",
        pubStatusOngoing = "连载中",
        pubStatusAbandoned = "弃坑",
        pubStatusHiatus = "休刊",

        complete = "完整",
        oneshot = "单本",
        authors = "作者",
        publisher = "出版商",
        language = "语言",
        releaseDate = "发布日期",
        ageRating = "年龄分级"
    ),
    booksFilter = BookFilterStrings(
        sort = "排序方式",
        sortNumberAsc = "升序",
        sortNumberDesc = "降序",

        sortFileNameAsc = "文件名升序",
        sortFileNameDesc = "文件名降序",
        sortReleaseDateAsc = "最新发布",
        sortReleaseDateDesc = "最早发布",

        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        authors = "作者",
        tags = "筛选标签",
    ),
    seriesView = SeriesViewStrings(
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "弃坑",
        statusHiatus = "休刊",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "垂直",
        readingDirectionWebtoon = "条漫 (Webtoon)",
    ),
    seriesEdit = SeriesEditStrings(
        title = "标题",
        sortTitle = "排序标题",
        summary = "简介",
        language = "语言",

        status = "状态",
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "弃坑",
        statusHiatus = "休刊",

        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "垂直",
        readingDirectionWebtoon = "条漫 (Webtoon)",
        publisher = "出版商",
        ageRating = "年龄分级",
        totalBookCount = "书籍总数"
    ),
    bookEdit = BookEditStrings(
        title = "标题",
        number = "编号",
        sortNumber = "排序编号",
        summary = "简介",
        releaseDate = "发布日期",
        isbn = "ISBN"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "每次扫描后自动清空回收站",
        scanForceModifiedTime = "强制使用目录修改时间",
        scanOnStartup = "启动时扫描",
        oneshotsDirectory = "单本目录",
        excludeDirectories = "排除目录",

        scanInterval = "扫描间隔",
        scanIntervalDisabled = "禁用",
        scanIntervalHourly = "每小时",
        scanIntervalEvery6H = "每 6 小时",
        scanIntervalEvery12H = "每 12 小时",
        scanIntervalDaily = "每天",
        scanIntervalWeekly = "每周",

        hashFiles = "计算文件哈希",
        hashPages = "计算页面哈希",
        analyzeDimensions = "分析页面尺寸",
        repairExtensions = "自动修复错误的文件扩展名",
        convertToCbz = "自动转换为 CBZ",
        seriesCover = "系列封面",
        coverFirst = "首本",
        coverFirstUnreadOrFirst = "首本未读，否则首本",
        coverFirstUnreadOrLast = "首本未读，否则末本",
        coverLast = "末本"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "内容限制",
        age = "年龄",
        labelsAllow = "仅允许的标签",
        labelsExclude = "排除的标签",
        ageRestriction = "年龄限制",
        ageRestrictionNone = "无限制",
        ageRestrictionAllowOnly = "仅允许低于",
        ageRestrictionExclude = "排除高于"
    ),
    reader = ReaderStrings(
        zoom = "缩放",
        readerType = "阅读器类型",
        readerPaged = "分页",
        readerPanels = "分镜",
        readerContinuous = "连续",
        stretchToFit = "拉伸小图以适应",
        decoder = "图像解码器/采样器",
        pagesInfo = "页面信息",
        pageNumber = "页",
        memoryUsage = "内存占用",
        pageDisplaySize = "显示尺寸",
        pageOriginalSize = "原始尺寸",
    ),
    pagedReader = PagedReaderStrings(
        scaleType = "缩放方式",
        scaleScreen = "适应屏幕",
        scaleFitWidth = "适应宽度",
        scaleFitHeight = "适应高度",
        scaleOriginal = "原始大小",
        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        layout = "页面布局",
        layoutSinglePage = "单页",
        layoutDoublePages = "双页",
        layoutDoublePagesNoCover = "双页（不含封面）",
        offsetPages = "偏移页面",
    ),
    continuousReader = ContinuousReaderStrings(
        sidePadding = "两侧留白",
        pageSpacing = "页间距",
        readingDirection = "阅读方向",
        readingDirectionTopToBottom = "从上到下",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
    ),
    settings = SettingsStrings(
        serverSettings = "服务器设置",
        thumbnailSize = "缩略图尺寸",
        thumbnailSizeDefault = "默认 (300px)",
        thumbnailSizeMedium = "中 (600px)",
        thumbnailSizeLarge = "大 (900px)",
        thumbnailSizeXLarge = "超大 (1200px)",

        thumbnailRegenTitle = "重新生成缩略图",
        thumbnailRegenBody = "缩略图尺寸已变更，是否重新生成书籍缩略图？",
        thumbnailRegenIfBigger = "是，仅当更大时重生成",
        thumbnailRegenAllBooks = "是，重生成所有书籍",
        thumbnailRegenNo = "否",

        deleteEmptyCollections = "扫描后删除空合集",
        deleteEmptyReadLists = "扫描后删除空阅读列表",
        taskPoolSize = "任务线程数",
        rememberMeDurationDays = "记住登录有效期（天）",
        renewRememberMeKey = "重新生成 RememberMe 密钥",
        serverPort = "服务器端口",
        serverContextPath = "基础 URL",
        requiresRestart = "重启后生效",
        serverSettingsDiscard = "放弃",
        serverSettingsSave = "保存更改",

        appTheme = "应用主题",
        appThemeDark = "深色",
        appThemeLight = "浅色",
        appThemeOled = "更暗",
        appLanguage = "语言 / Language",
        appLanguageSystem = "跟随系统",
        appLanguageEnglish = "English",
        appLanguageChineseSimplified = "简体中文",
        imageCardSize = "网格视图中的封面卡片尺寸（最小显示尺寸）",
        decoder = "图像解码器/采样器",
        epubReaderTypeKomga = "Komga EPUB 阅读器",
        epubReaderTypeTtsu = "ッツ EBook Reader"
    ),
    errorCodes = ErrorCodes(
        err1000 = "分析时无法访问该文件",
        err1001 = "不支持的媒体类型",
        err1002 = "不支持加密的 RAR 压缩包",
        err1003 = "不支持固实 (Solid) RAR 压缩包",
        err1004 = "不支持分卷 RAR 压缩包",
        err1005 = "分析书籍时发生未知错误",
        err1006 = "书籍不包含任何页面",
        err1007 = "部分条目无法被分析",
        err1008 = "获取书籍条目时发生未知错误",
        err1009 = "已存在同名的阅读列表",
        err1015 = "解析 ComicRack CBL 时出错",
        err1016 = "目录无法访问或不是一个目录",
        err1017 = "无法扫描已属于现有书库的文件夹",
        err1018 = "未找到文件",
        err1019 = "无法导入已属于现有书库的文件",
        err1020 = "待升级的书籍不属于指定的系列",
        err1021 = "目标文件已存在",
        err1022 = "新导入的书籍无法被扫描",
        err1023 = "该书已存在于阅读列表中",
        err1024 = "OAuth2 登录错误：缺少 email 属性",
        err1025 = "OAuth2 登录错误：本地不存在使用该邮箱的用户",
        err1026 = "OpenID Connect 登录错误：邮箱未验证",
        err1027 = "OpenID Connect 登录错误：缺少 email_verified 属性",
        err1028 = "OpenID Connect 登录错误：缺少 email 属性",
        err1029 = "ComicRack CBL 不包含任何 Book 元素",
        err1030 = "ComicRack CBL 缺少 Name 元素",
        err1031 = "ComicRack CBL 中的 Book 缺少 series 或 number",
        err1032 = "EPUB 文件的媒体类型不正确",
        err1033 = "部分条目缺失",
        err1034 = "已存在使用该备注的 API 密钥",
        err1035 = "获取 EPUB 目录 (TOC) 时出错",
        err1036 = "获取 EPUB 标记 (Landmarks) 时出错",
        err1037 = "获取 EPUB 页面列表时出错",
        err1038 = "获取 EPUB Divina 页面时出错",
        err1039 = "获取 EPUB 位置时出错",
    ),
    komf = KomfStrings(
        providerSettings = KomfProviderSettingsStrings(
            providerAniList = "AniList",
            providerBangumi = "Bangumi",
            providerBookWalker = "Bookwalker Global",
            providerComicVine = "ComicVine",
            providerHentag = "Hentag",
            providerKodansha = "Kodansha US",
            providerMal = "MyAnimeList",
            providerMangaBaka = "MangaBaka",
            providerMangaUpdates = "MangaUpdates",
            providerMangaDex = "MangaDex",
            providerNautiljon = "Nautiljon",
            providerYenPress = "YenPress",
            providerViz = "Viz",
            providerWebtoons = "Webtoons",
        )
    ),
    imageSettings = ImageSettingsStrings(
        upsamplingMode = "上采样模式",
        upsamplingModeNearest = "最近邻 (Nearest neighbour)",
        upsamplingModeBilinear = "双线性 (Bilinear)",
        upsamplingModeMitchell = "双三次 Mitchell",
        upsamplingModeCatmullRom = "双三次 Catmull-Rom",
        downsamplingKernel = "下采样核",
        downsamplingKernelNearest = "最近邻 (Nearest neighbour)",
        downsamplingKernelLinear = "线性 (Linear)",
        downsamplingKernelCubic = "三次 (Cubic)",
        downsamplingKernelMitchell = "Mitchell",
        downsamplingKernelLanczos2 = "Lanczos2",
        downsamplingKernelLanczos3 = "Lanczos3",
        downsamplingKernelMKS2013 = "Magic Kernel Sharp 2013",
        downsamplingKernelMKS2021 = "Magic Kernel Sharp 2021",
        downsamplingKernelDefault = "默认",
        onnxRuntimeExecutionProvider = "ONNX Runtime 执行后端",

        onnxRuntimeUpscaleMode = "ONNX Runtime 放大模式",
        onnxRuntimeUpscaleModeNone = "禁用",
        onnxRuntimeUpscaleModeUserModel = "用户指定模型",
        onnxRuntimeUpscaleModeMangaJaNai = "MangaJaNai 预设"
    ),
    legacy = LegacyStrings(
        mapOf(
            "Settings" to "设置",
            "Appearance" to "外观",
            "Account Settings" to "账户设置",
            "Epub Reader Settings" to "EPUB 阅读器设置",
            "Offline mode" to "离线模式",
            "App Updates" to "应用更新",
            "Image Reader" to "图像阅读器",
            "Network Connection" to "网络连接",
            "Automatically use LAN address" to "自动使用局域网地址",
            "LAN server address" to "局域网服务器地址",
            "Check connection" to "检测连接",
            "Current server address" to "当前服务器地址",
            "Using primary server address" to "正在使用主服务器地址",
            "Checking LAN address" to "正在检测局域网地址",
            "Using LAN address" to "正在使用局域网地址",
            "LAN address is unreachable" to "局域网地址不可达",
            "Server Settings" to "服务器设置",
            "Komf Settings" to "Komf 设置",
            "Metadata Update Jobs" to "元数据更新任务",
            "Metadata Providers Settings" to "元数据源设置",
            "Notification Settings" to "通知设置",
            "Komga Login" to "Komga 登录",
            "Komga webui" to "Komga Web 界面",
            "Connection" to "连接",
            "Komga Processing" to "Komga 处理",
            "Kavita Processing" to "Kavita 处理",
            "Providers" to "元数据源",
            "Notifications" to "通知",
            "Job History" to "任务历史",
            "Nothing to show" to "暂无内容",
            "Error" to "错误",
            "Cancel" to "取消",
            "Confirm" to "确认",
            "Save" to "保存",
            "Discard" to "放弃",
            "Delete" to "删除",
            "Edit" to "编辑",
            "Download" to "下载",
            "Read" to "阅读",
            "Read incognito" to "隐身阅读",
            "Search" to "搜索",
            "Reset" to "重置",
            "Retry" to "重试",
            "Close" to "关闭",
            "Done" to "完成",
            "Create" to "创建",
            "Any" to "任意",
            "None" to "无",
            "Parent" to "上一级",
            "Books" to "书籍",
            "Analyze" to "分析",
            "Refresh metadata" to "刷新元数据",
            "Add to read list" to "添加到阅读列表",
            "Add to collection" to "添加到合集",
            "Mark as read" to "标为已读",
            "Mark as unread" to "标为未读",
            "Delete downloaded" to "删除下载内容",
            "Delete downloaded Book" to "删除已下载书籍",
            "Delete downloaded series" to "删除已下载系列",
            "Delete downloaded Library" to "删除已下载书库",
            "Delete Book" to "删除书籍",
            "Delete Series" to "删除系列",
            "Delete Library" to "删除书库",
            "Delete Collection" to "删除合集",
            "Delete Read List" to "删除阅读列表",
            "Analyze library" to "分析书库",
            "Scan library files" to "扫描书库文件",
            "Scan library files (deep)" to "深度扫描书库文件",
            "Refresh metadata for library" to "刷新书库元数据",
            "Empty trash for library" to "清空书库回收站",
            "Empty trash" to "清空回收站",
            "New version is available" to "发现新版本",
            "Recent downloads" to "最近下载",
            "Clear all" to "全部清除",
            "The search returned no results" to "没有找到搜索结果",
            "Try searching for something else" to "换个关键词试试",
            "No books" to "暂无书籍",
            "Book Filters" to "书籍筛选",
            "Point Type" to "点类型",
            "Output Levels" to "输出色阶",
            "Input Levels" to "输入色阶",
            "Library's root folder" to "书库根目录",
            "Add to collection" to "添加到合集",
            "Add to read list" to "添加到阅读列表",
            "Search or create collection" to "搜索或创建合集",
            "Search or create read list" to "搜索或创建阅读列表",
            "Edit User" to "编辑用户",
            "Roles" to "角色",
            "Shared Libraries" to "共享书库",
            "Content Restriction" to "内容限制",
            "Administrator" to "管理员",
            "Page Streaming" to "页面流式传输",
            "File Download" to "文件下载",
            "Share Libraries" to "共享书库",
            "New password" to "新密码",
            "Repeat new password" to "重复新密码",
            "Change Password" to "修改密码",
            "Add" to "添加",
            "Name" to "名称",
            "Root folder" to "根目录",
            "Browse" to "浏览",
            "Manual ordering" to "手动排序",
            "Scan for these file types" to "扫描这些文件类型",
            "Comic Book archives" to "漫画压缩包",
            "CANCEL" to "取消",
            "CHOOSE" to "选择",
            "GENERAL" to "通用",
            "TAGS" to "标签",
            "LINKS" to "链接",
            "AUTHORS" to "作者",
            "SCANNER" to "扫描器",
            "OPTIONS" to "选项",
            "METADATA" to "元数据",
            "POSTER" to "封面",
            "SHARING" to "共享",
            "ALTERNATE TITLES" to "其他标题",
            "Read lists" to "阅读列表",
            "Series" to "系列",
            "Collections" to "合集",
            "Read Lists" to "阅读列表",
            "All" to "全部",
            "Keep reading" to "继续阅读",
            "On deck" to "待读",
            "Recently released books" to "最近发布的书籍",
            "Recently added books" to "最近添加的书籍",
            "Recently added series" to "最近添加的系列",
            "Recently updated series" to "最近更新的系列",
            "Recently read books" to "最近阅读的书籍",
            "Operator" to "运算符",
            "Condition" to "条件",
            "Add condition" to "添加条件",
            "Sort" to "排序",
            "Direction" to "方向",
            "Ascending" to "升序",
            "Descending" to "降序",
            "AnyOf" to "任一条件",
            "AllOf" to "全部条件",
            "Any" to "任意",
            "All" to "全部",
            "Equals" to "等于",
            "NotEquals" to "不等于",
            "IsNull" to "为空",
            "IsNotNull" to "不为空",
            "True" to "是",
            "False" to "否",
            "Contains" to "包含",
            "DoesNotContain" to "不包含",
            "BeginsWith" to "开头为",
            "DoesNotBeginWith" to "开头不是",
            "EndsWith" to "结尾为",
            "DoesNotEndWith" to "结尾不是",
            "IsBefore" to "早于",
            "IsAfter" to "晚于",
            "IsInLast" to "最近",
            "IsNotInLast" to "不在最近",
            "EqualTo" to "等于",
            "NotEqualTo" to "不等于",
            "GreaterThan" to "大于",
            "LessThan" to "小于",
            "CreatedDate" to "创建日期",
            "LastModified" to "最后修改",
            "LastModifiedDate" to "最后修改日期",
            "SeriesTitle" to "系列标题",
            "PagesCount" to "页数",
            "BookCount" to "书籍数",
            "ReleaseDate" to "发布日期",
            "ReadDate" to "阅读日期",
            "Unsorted" to "不排序",
            "TitleSort" to "排序标题",
            "NumberSort" to "排序编号",
            "AgeRating" to "年龄分级",
            "Collection" to "合集",
            "Complete" to "完整",
            "Deleted" to "已删除",
            "MediaProfile" to "媒体规格",
            "MediaStatus" to "媒体状态",
            "Oneshot" to "单本",
            "Poster" to "封面",
            "ReadList" to "阅读列表",
            "ReadStatus" to "阅读状态",
            "Series" to "系列",
            "Status" to "状态",
            "Tag" to "标签",
            "Title" to "标题",
            "Number" to "编号",
            "Selected" to "已选择",
            "Type" to "类型",
            "EPUB" to "EPUB",
            "PDF" to "PDF",
            "DIVINA" to "DIVINA",
            "READY" to "就绪",
            "ERROR" to "错误",
            "UNSUPPORTED" to "不支持",
            "UNKNOWN" to "未知",
            "Role" to "角色",
            "Value" to "值",
            "Sharing Label" to "共享标签",
            "Author" to "作者",
            "Authors" to "作者",
            "Genre" to "类型",
            "Genres" to "类型",
            "Language" to "语言",
            "Publisher" to "出版商",
            "Publishers" to "出版商",
            "Writers" to "编剧",
            "Writer" to "作者",
            "Pencillers" to "线稿",
            "Penciller" to "线稿",
            "Inkers" to "描线",
            "Inker" to "描线",
            "Colorists" to "上色",
            "Colorist" to "上色",
            "Letterers" to "嵌字",
            "Letterer" to "嵌字",
            "Editors" to "编辑",
            "Editor" to "编辑",
            "Translators" to "翻译",
            "Translator" to "翻译",
            "Cover Artists" to "封面作者",
            "Cover" to "封面",
            "Size" to "大小",
            "Format" to "格式",
            "File" to "文件",
            "Release date:" to "发布日期：",
            "Read progress:" to "阅读进度：",
            "Last read:" to "上次阅读：",
            "page left" to "页未读",
            "pages left" to "页未读",
            "Expand" to "展开",
            "Collapse" to "收起",
            "Age" to "年龄",
            "Collection" to "合集",
            "Read List" to "阅读列表",
            "Title" to "标题",
            "Number" to "编号",
            "Sort Number" to "排序编号",
            "Summary" to "简介",
            "Release Date" to "发布日期",
            "Label" to "标签",
            "Tags" to "标签",
            "Parody" to "原作",
            "Character" to "角色",
            "Group" to "社团",
            "Female" to "女性",
            "Male" to "男性",
            "Category" to "分类",
            "Other tags" to "其他标签",
            "Alternative titles" to "其他标题",
            "Links" to "链接",
            "Search all..." to "搜索全部...",
            "Copied to clipboard" to "已复制到剪贴板",
            "Copy stacktrace to clipboard" to "复制错误堆栈",
            "Restart" to "重启",
            "Exit" to "退出",
            "Storage location" to "存储位置",
            "Change location" to "更改位置",
            "Reset to internal" to "重置为内部存储",
            "Download Complete " to "下载完成 ",
            "Users" to "用户",
            "Downloads" to "下载",
            "Logs" to "日志",
            "Go online" to "切回在线",
            "Go offline as current user" to "以当前用户离线使用",
            "Project on Github" to "GitHub 项目",
            "Reader Type" to "阅读器类型",
            "TTSU reader description" to "ッツ EBook Reader 适合日文 EPUB 阅读，支持目录、阅读设置和本地阅读偏好。首次打开会加载整本书，超大 EPUB 可能加载较慢。",
            "Load small previews when dragging navigation slider" to "拖动导航滑块时加载小预览图",
            "can be slow for high resolution images" to "高分辨率图片可能较慢",
            "Volume keys navigation" to "音量键翻页",
            "Clear image cache" to "清除图像缓存",
            "Panels reader uses automatic panel detection to navigate one panel at a time" to "分镜阅读器会自动识别画面分格，并按单个分镜逐步阅读",
            "Downloading panel detection model" to "正在下载分镜检测模型",
            "Download Model" to "下载模型",
            "Re-download Model" to "重新下载模型",
            "Installed" to "已安装",
            "Refresh libraries" to "刷新书库",
            "Libraries refreshed" to "书库已刷新",
            "Library refresh is unavailable in offline mode" to "离线模式下无法刷新书库",
            "Add library" to "添加书库",
            "Unavailable" to "不可用",
            "Server Management" to "服务器管理",
            "Scan all libraries" to "扫描所有书库",
            "Check folders for new or removed books.\nUses the last modified time of parent folders" to "检查文件夹中新增或移除的书籍。\n使用父文件夹的最后修改时间判断变化",
            "Scan" to "扫描",
            "Deep scan all libraries" to "深度扫描所有书库",
            "Force the scanner to compare all scanned books with the ones stored in the database" to "强制扫描器比较所有已扫描书籍与数据库中记录的书籍",
            "Deep Scan" to "深度扫描",
            "Empty trash for all libraries" to "清空所有书库回收站",
            "Delete items marked as unavailable" to "删除标记为不可用的项目",
            "Empty" to "清空",
            "Cancel all tasks" to "取消所有任务",
            "Cancel all currently running tasks" to "取消所有正在运行的任务",
            "Shutdown" to "关闭服务器",
            "Stop Komga application process" to "停止 Komga 应用进程",
            "Empty trash for all libraries confirmation" to "默认情况下，媒体服务器不会立即移除媒体信息，以便临时断开硬盘时保留数据。清空回收站会删除所有缺失媒体的信息。",
            "Shut down server" to "关闭服务器",
            "Are you sure you want to stop Komga?" to "确定要停止 Komga 吗？",
            "Stop" to "停止",
            "Add User" to "添加用户",
            "Add user" to "添加用户",
            "Cover image" to "封面图片",
            "Add image" to "添加图片",
            "Upload image" to "上传图片",
            "Select image" to "选择图片",
            "Choose an image - drag and drop" to "选择图片，或拖放到此处",
            "Book Filter" to "书籍筛选",
            "Series Filter" to "系列筛选",
            "Add Filter" to "添加筛选",
            "Reset to default" to "重置为默认",
            "Reset homescreen filters to default?" to "将首页筛选重置为默认值？",
            "Reached the start of the series" to "已到达系列开头",
            "Reached the end of the series" to "已到达系列末尾",
            "Previous:" to "上一项：",
            "Current:" to "当前：",
            "Finished:" to "已完成：",
            "Next:" to "下一项：",
            "Downloading..." to "正在下载...",
            "Processing..." to "正在处理...",
            "Reading mode" to "阅读模式",
            "Image settings" to "图像设置",
            "active" to "已启用",
            "Flash Duration" to "闪烁时长",
            "Flash every" to "闪烁间隔",
            "Side padding" to "侧边距",
            "Page spacing" to "页面间距",
            "slower but potentially more accurate" to "速度较慢，但可能更准确",
            "ONNX Runtime" to "ONNX Runtime",
            "Download ONNX Runtime" to "下载 ONNX Runtime",
            "Update ONNX Runtime" to "更新 ONNX Runtime",
            "Choose ONNX Runtime version" to "选择 ONNX Runtime 版本",
            "Downloading ONNX Runtime" to "正在下载 ONNX Runtime",
            "Update or download another version of ONNX Runtime" to "更新或下载其他版本的 ONNX Runtime",
            "Upscaler Settings" to "放大设置",
            "Panel Detection" to "分镜检测",
            "Aggregation settings" to "聚合设置",
            "Cover settings" to "封面设置",
            "Title Settings" to "标题设置",
            "Default values" to "默认值",
            "SERIES METADATA" to "系列元数据",
            "BOOK METADATA" to "书籍元数据",
            "PROVIDER SETTINGS" to "源设置",
            "MangaBaka Offline Database" to "MangaBaka 离线数据库",
            "Downloading MangaBaka database" to "正在下载 MangaBaka 数据库",
            "Connected" to "已连接",
            "Add New Discord Webhook" to "添加 Discord Webhook",
            "Notification Template" to "通知模板",
            "Delete all server data" to "删除全部服务器数据",
            "Delete user data" to "删除用户数据",
            "Delete all local data for server" to "删除该服务器的全部本地数据",
            "Delete all local data for user" to "删除该用户的全部本地数据",
        )
    ),
)
