package snd.komelia.ui.strings

/**
 * 简体中文 (zh-CN) 翻译。
 *
 * 翻译规范见 `docs/i18n/glossary_zh-CN.md` 与 `docs/i18n/CONTRIBUTING_zh-CN.md`：
 * - 品牌名（Komelia / Komga / Komf）与第三方元数据提供方名称（AniList / Bangumi / MangaDex 等）保留原名
 * - 图像处理算法名（Lanczos / Mitchell / Catmull-Rom / MKS / ONNX 等）保留英文，避免误导
 * - 按钮使用动词，标题使用名词；避免句末加全角句号
 *
 * 注意：本文件仅翻译已被 `LocalStrings` 集中管理的字符串。
 * UI 中仍有大量硬编码英文字符串（约 580 处），将在后续 PR 中逐步迁移到 `AppStrings`，再补充翻译。
 */
val ZhCnStrings = AppStrings(
    filters = FilterStrings(
        anyValue = "任意",

        filterTagsSearch = "搜索标签",
        filterTagsReset = "重置",
        filterTagsGenreLabel = "类型",
        filterTagsTagsLabel = "标签",
        filterTagsShowMore = "展开",
        filterTagsShowLess = "收起",
        includeIfAllMatch = "全部匹配",
        includeIfAnyMatch = "任一匹配",
        excludeIfAllMatch = "全部匹配",
        excludeIfAnyMatch = "任一匹配",
    ),
    seriesFilter = SeriesFilterStrings(
        resetFilters = "重置筛选",
        hideFilters = "隐藏筛选",
        anyValue = "任意",
        search = "搜索",

        sort = "排序方式",
        sortTitleAsc = "标题升序",
        sortTitleDesc = "标题降序",
        sortDateAddedAsc = "最早添加",
        sortDateAddedDesc = "最近添加",
        sortReleaseDateAsc = "最早发布",
        sortReleaseDateDesc = "最新发布",
        sortUpdatedAsc = "最早更新",
        sortUpdatedDesc = "最近更新",
        sortFolderNameAsc = "文件夹名升序",
        sortFolderNameDesc = "文件夹名降序",
        sortBooksCountAsc = "书籍数从少到多",
        sortBooksCountDesc = "书籍数从多到少",

        filterTagsLabel = "筛选标签",
        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        publicationStatus = "出版状态",
        pubStatusEnded = "已完结",
        pubStatusOngoing = "连载中",
        pubStatusAbandoned = "弃坑",
        pubStatusHiatus = "休刊",

        complete = "完整",
        oneshot = "单本",
        authors = "作者",
        publisher = "出版商",
        language = "语言",
        releaseDate = "发布日期",
        ageRating = "年龄分级"
    ),
    booksFilter = BookFilterStrings(
        sort = "排序方式",
        sortNumberAsc = "升序",
        sortNumberDesc = "降序",

        sortFileNameAsc = "文件名升序",
        sortFileNameDesc = "文件名降序",
        sortReleaseDateAsc = "最新发布",
        sortReleaseDateDesc = "最早发布",

        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        authors = "作者",
        tags = "筛选标签",
    ),
    seriesView = SeriesViewStrings(
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "弃坑",
        statusHiatus = "休刊",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "垂直",
        readingDirectionWebtoon = "条漫 (Webtoon)",
    ),
    seriesEdit = SeriesEditStrings(
        title = "标题",
        sortTitle = "排序标题",
        summary = "简介",
        language = "语言",

        status = "状态",
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "弃坑",
        statusHiatus = "休刊",

        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "垂直",
        readingDirectionWebtoon = "条漫 (Webtoon)",
        publisher = "出版商",
        ageRating = "年龄分级",
        totalBookCount = "书籍总数"
    ),
    bookEdit = BookEditStrings(
        title = "标题",
        number = "编号",
        sortNumber = "排序编号",
        summary = "简介",
        releaseDate = "发布日期",
        isbn = "ISBN"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "每次扫描后自动清空回收站",
        scanForceModifiedTime = "强制使用目录修改时间",
        scanOnStartup = "启动时扫描",
        oneshotsDirectory = "单本目录",
        excludeDirectories = "排除目录",

        scanInterval = "扫描间隔",
        scanIntervalDisabled = "禁用",
        scanIntervalHourly = "每小时",
        scanIntervalEvery6H = "每 6 小时",
        scanIntervalEvery12H = "每 12 小时",
        scanIntervalDaily = "每天",
        scanIntervalWeekly = "每周",

        hashFiles = "计算文件哈希",
        hashPages = "计算页面哈希",
        analyzeDimensions = "分析页面尺寸",
        repairExtensions = "自动修复错误的文件扩展名",
        convertToCbz = "自动转换为 CBZ",
        seriesCover = "系列封面",
        coverFirst = "首本",
        coverFirstUnreadOrFirst = "首本未读，否则首本",
        coverFirstUnreadOrLast = "首本未读，否则末本",
        coverLast = "末本"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "内容限制",
        age = "年龄",
        labelsAllow = "仅允许的标签",
        labelsExclude = "排除的标签",
        ageRestriction = "年龄限制",
        ageRestrictionNone = "无限制",
        ageRestrictionAllowOnly = "仅允许低于",
        ageRestrictionExclude = "排除高于"
    ),
    reader = ReaderStrings(
        zoom = "缩放",
        readerType = "阅读器类型",
        readerPaged = "分页",
        readerPanels = "分镜",
        readerContinuous = "连续",
        stretchToFit = "拉伸小图以适应",
        decoder = "图像解码器/采样器",
        pagesInfo = "页面信息",
        pageNumber = "页",
        memoryUsage = "内存占用",
        pageDisplaySize = "显示尺寸",
        pageOriginalSize = "原始尺寸",
    ),
    pagedReader = PagedReaderStrings(
        scaleType = "缩放方式",
        scaleScreen = "适应屏幕",
        scaleFitWidth = "适应宽度",
        scaleFitHeight = "适应高度",
        scaleOriginal = "原始大小",
        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        layout = "页面布局",
        layoutSinglePage = "单页",
        layoutDoublePages = "双页",
        layoutDoublePagesNoCover = "双页（不含封面）",
        offsetPages = "偏移页面",
    ),
    continuousReader = ContinuousReaderStrings(
        sidePadding = "两侧留白",
        pageSpacing = "页间距",
        readingDirection = "阅读方向",
        readingDirectionTopToBottom = "从上到下",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
    ),
    settings = SettingsStrings(
        serverSettings = "服务器设置",
        thumbnailSize = "缩略图尺寸",
        thumbnailSizeDefault = "默认 (300px)",
        thumbnailSizeMedium = "中 (600px)",
        thumbnailSizeLarge = "大 (900px)",
        thumbnailSizeXLarge = "超大 (1200px)",

        thumbnailRegenTitle = "重新生成缩略图",
        thumbnailRegenBody = "缩略图尺寸已变更，是否重新生成书籍缩略图？",
        thumbnailRegenIfBigger = "是，仅当更大时重生成",
        thumbnailRegenAllBooks = "是，重生成所有书籍",
        thumbnailRegenNo = "否",

        deleteEmptyCollections = "扫描后删除空合集",
        deleteEmptyReadLists = "扫描后删除空阅读列表",
        taskPoolSize = "任务线程数",
        rememberMeDurationDays = "记住登录有效期（天）",
        renewRememberMeKey = "重新生成 RememberMe 密钥",
        serverPort = "服务器端口",
        serverContextPath = "基础 URL",
        requiresRestart = "重启后生效",
        serverSettingsDiscard = "放弃",
        serverSettingsSave = "保存更改",

        appTheme = "应用主题",
        appThemeDark = "深色",
        appThemeLight = "浅色",
        appThemeOled = "更暗",
        appLanguage = "语言 / Language",
        appLanguageSystem = "跟随系统",
        appLanguageEnglish = "English",
        appLanguageChineseSimplified = "简体中文",
        imageCardSize = "网格视图中的封面卡片尺寸（最小显示尺寸）",
        decoder = "图像解码器/采样器",
        epubReaderTypeKomga = "Komga EPUB 阅读器",
        epubReaderTypeTtsu = "ッツ EBook Reader"
    ),
    errorCodes = ErrorCodes(
        err1000 = "分析时无法访问该文件",
        err1001 = "不支持的媒体类型",
        err1002 = "不支持加密的 RAR 压缩包",
        err1003 = "不支持固实 (Solid) RAR 压缩包",
        err1004 = "不支持分卷 RAR 压缩包",
        err1005 = "分析书籍时发生未知错误",
        err1006 = "书籍不包含任何页面",
        err1007 = "部分条目无法被分析",
        err1008 = "获取书籍条目时发生未知错误",
        err1009 = "已存在同名的阅读列表",
        err1015 = "解析 ComicRack CBL 时出错",
        err1016 = "目录无法访问或不是一个目录",
        err1017 = "无法扫描已属于现有书库的文件夹",
        err1018 = "未找到文件",
        err1019 = "无法导入已属于现有书库的文件",
        err1020 = "待升级的书籍不属于指定的系列",
        err1021 = "目标文件已存在",
        err1022 = "新导入的书籍无法被扫描",
        err1023 = "该书已存在于阅读列表中",
        err1024 = "OAuth2 登录错误：缺少 email 属性",
        err1025 = "OAuth2 登录错误：本地不存在使用该邮箱的用户",
        err1026 = "OpenID Connect 登录错误：邮箱未验证",
        err1027 = "OpenID Connect 登录错误：缺少 email_verified 属性",
        err1028 = "OpenID Connect 登录错误：缺少 email 属性",
        err1029 = "ComicRack CBL 不包含任何 Book 元素",
        err1030 = "ComicRack CBL 缺少 Name 元素",
        err1031 = "ComicRack CBL 中的 Book 缺少 series 或 number",
        err1032 = "EPUB 文件的媒体类型不正确",
        err1033 = "部分条目缺失",
        err1034 = "已存在使用该备注的 API 密钥",
        err1035 = "获取 EPUB 目录 (TOC) 时出错",
        err1036 = "获取 EPUB 标记 (Landmarks) 时出错",
        err1037 = "获取 EPUB 页面列表时出错",
        err1038 = "获取 EPUB Divina 页面时出错",
        err1039 = "获取 EPUB 位置时出错",
    ),
    komf = KomfStrings(
        providerSettings = KomfProviderSettingsStrings(
            providerAniList = "AniList",
            providerBangumi = "Bangumi",
            providerBookWalker = "Bookwalker Global",
            providerComicVine = "ComicVine",
            providerHentag = "Hentag",
            providerKodansha = "Kodansha US",
            providerMal = "MyAnimeList",
            providerMangaBaka = "MangaBaka",
            providerMangaUpdates = "MangaUpdates",
            providerMangaDex = "MangaDex",
            providerNautiljon = "Nautiljon",
            providerYenPress = "YenPress",
            providerViz = "Viz",
            providerWebtoons = "Webtoons",
        )
    ),
    imageSettings = ImageSettingsStrings(
        upsamplingMode = "上采样模式",
        upsamplingModeNearest = "最近邻 (Nearest neighbour)",
        upsamplingModeBilinear = "双线性 (Bilinear)",
        upsamplingModeMitchell = "双三次 Mitchell",
        upsamplingModeCatmullRom = "双三次 Catmull-Rom",
        downsamplingKernel = "下采样核",
        downsamplingKernelNearest = "最近邻 (Nearest neighbour)",
        downsamplingKernelLinear = "线性 (Linear)",
        downsamplingKernelCubic = "三次 (Cubic)",
        downsamplingKernelMitchell = "Mitchell",
        downsamplingKernelLanczos2 = "Lanczos2",
        downsamplingKernelLanczos3 = "Lanczos3",
        downsamplingKernelMKS2013 = "Magic Kernel Sharp 2013",
        downsamplingKernelMKS2021 = "Magic Kernel Sharp 2021",
        downsamplingKernelDefault = "默认",
        onnxRuntimeExecutionProvider = "ONNX Runtime 执行后端",

        onnxRuntimeUpscaleMode = "ONNX Runtime 放大模式",
        onnxRuntimeUpscaleModeNone = "禁用",
        onnxRuntimeUpscaleModeUserModel = "用户指定模型",
        onnxRuntimeUpscaleModeMangaJaNai = "MangaJaNai 预设"
    ),
)
