ALTER TABLE TASK ADD COLUMN completed_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TASK ADD COLUMN total_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TASK ADD COLUMN speed_bytes_per_second INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TASK ADD COLUMN display_title TEXT;
ALTER TABLE TASK ADD COLUMN error_message TEXT;
